### ISSUE TITLE
ID == tyrant_optimize

### ISSUE THREAD

**Issue by FKuerten** [iteratedecks/fansiteSubmission#2]
Last time I checked (which is a month ago)
IterateDecks and tyrant_optimize where distinct projects.
Yet the links in the readme suggest they are the same.

**Comment by hunterhogan** [comment]
MrHen wrote the Python wrapper, andor9 modified the wrapper to work for both IterateDecks and tyrant_optimize and made a pull request for id/FS. I tested andor9’s version of the wrapper on id and it works, including the --runforever switch. Therefore, I wrote the readme to cover both projects.

**Comment by MrHen** [comment]
dfcf106b4485b1d27293f77af25effe7034d8966
