### ISSUE TITLE
Download latest xml loop

### ISSUE THREAD

**Issue by hunterhogan** [iteratedecks/fansiteSubmission#5]
I run the wrapper, and I get this.

Using iteratedecks version 1.0.5 with 100007 sims per deck
Requesting session id...
ERROR 104:      cards.xml is out of date. You need to download the latest Tyrant xml files.
Would you like to download the latest Tyrant xml files (y/n)?

I say yes, it downloads the files (dates/times change). I run again, but same problem. I downloaded using the old ED GUI, copy the files over. Same problem.

I used the XML files included in the zip file (1.0.5). Same problem.

No idea what to test next. 

Oh, and I have not seen this issue before, either with ID or TO. I have used the wrapper to download the files before, and it has always worked.

**Comment by MrHen** [comment]
Hm, that's odd. I used it earlier and it worked but now it is broken for me too.

**Comment by FKuerten** [comment]
Could also be a bug on fansite.

**Comment by MrHen** [comment]
I talked with sss1 and the problem was due to a cards.xml update getting missed because it didn't bump the version number of Tyrant. Everything should be working again.
